"""your message

Revision ID: 4e3167830d1a
Revises: b24fa509cb1b
Create Date: 2024-07-17 14:50:23.416220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3167830d1a'
down_revision = 'b24fa509cb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
